#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 31, 2020 02:26:41 AM IST  platform: Linux

import sys
from tkinter.filedialog import askopenfilename
import mainwin
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global lista
    lista = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top



def selectfile():
    print('mainwin_support.selectfile')
    global filename
    filename = askopenfilename()
    lista.set(filename)
    sys.stdout.flush()

def stopfinder():
    print('stopfinder')

    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import mainwin
    mainwin.vp_start_gui()




